### ISSUE TITLE
Why a 500 Ohm resistor

### ISSUE THREAD

**Issue by netdata-be** [philibertc/micronova_controller#38]
Hi there,

I'm developing my own PCB because and I'm using your project as a base, thanks for that !

I'm just wondering why you picked a 500 ohm resistor, let me try to explain:

- 5V / 510 Ohm =  0,0098 A  == 9,8 mA
- 3,3V / 510 Ohm =  0,00064 == 6,4 mA

Since an optocoupler is just a LED it is designed to have 20mA over the IR LED

This means the ideal resistor should be:

- 5V / 0,02 A = 250 Ohm
- 3,3 V / 0,02 A =  165 Ohm 

I'm guessing the led emits enough IR to activate the collector and thus work.
Or I'm I missing something?

**Comment by philibertc** [comment]
Hello,

You are right, 250 Ohms resistors would be enough for that, but using about 500 allows to have a margin, because of the variable quality on sites like AliExpress but also to draw as little as possible on the 5V supplied by the stove.

Best Regards,
Philibert

PS: I'm closing this issue but you can still comment
https://github.com/philibertc/micronova_controller/issues/34#issuecomment-1053326781
